### ISSUE TITLE
Feature: Ability to reset Steam and Game directory path

### ISSUE THREAD

**Issue by koloml** [ast-r/flatout2-launcher#1]
Currently, once user set path for the Steam and/or Game, they will be unable to change it without manually modifying it in configuration file. Probably it's better to give the user ability to change it directly from the launcher's settings.

**Comment by ast-r** [comment]
Fixed in [fb17339](https://github.com/ast-r/flatout2-launcher/commit/fb17339d301361f17d69d00e6b5a5fa7f8ff0dcb)
