### ISSUE TITLE
Missing game and Steam path validation

### ISSUE THREAD

**Issue by koloml** [ast-r/flatout2-launcher#2]
If you set path for the Steam/game but the path is invalid, launcher still will try to execute commands. It's better to do minimal validation of the path (like, name of the executable).

Partially related to #1. When path is set to invalid path then user will be unable to change it without editing configuration file.

**Comment by ast-r** [comment]
Fixed in [fb17339](https://github.com/ast-r/flatout2-launcher/commit/fb17339d301361f17d69d00e6b5a5fa7f8ff0dcb)
